library(shiny)
library(R6)
library(caret)
library(caretEnsemble)
library(dplyr)
library(future)
library(DT)
library(cookies)
source("server/server.R")
source("ui/ui.R")

options(shiny.host = "127.0.0.1")
options(shiny.port = 6698)

shinyApp(ui = ui, server = server)
